-- Funcinários com duas ou mais locações
SELECT E.ID, E.NAME, E.PHONE_NUMBER, E.CONTRACT_DATE, P.DESCRIPTION, COUNT(L.EMPLOYEE_ID)
AS NUMBER_LOCATIONS FROM EMPLOYEES AS E
INNER JOIN POSITIONS AS P ON (E.POSITION_ID = P.ID)
INNER JOIN LOCATIONS AS L ON (L.EMPLOYEE_ID = E.ID)
GROUP BY EMPLOYEE_ID HAVING COUNT(L.EMPLOYEE_ID) >= 2;
