-- Clientes com duas ou mais locações
SELECT C.*, COUNT(L.CUSTOMER_ID) AS NUMBER_LOCATIONS
FROM CUSTOMERS AS C
INNER JOIN LOCATIONS AS L ON (L.CUSTOMER_ID = C.ID)
GROUP BY CUSTOMER_ID HAVING COUNT(L.CUSTOMER_ID) >= 2;
